- name: provision devbox-firefox-buildtools
  hosts: localhost
  roles:
  - firefox-buildtools         ### install and configure tools needed to build firefox
  - container-cleanup          ### cleanup container
