---
- name: install firefox build dependencies
  apt: name={{item}} update_cache=yes cache_valid_time=3600
  with_items:
  - zip
  - unzip
  - mercurial
  - g++
  - make
  - autoconf2.13
  - yasm
  - libgtk2.0-dev
  - libglib2.0-dev
  - libdbus-1-dev
  - libdbus-glib-1-dev
  - libasound2-dev
  - libcurl4-openssl-dev
  - libiw-dev
  - libxt-dev
  - mesa-common-dev
  - libgstreamer0.10-dev
  - libgstreamer-plugins-base0.10-dev
  - libpulse-dev
