---
- name: install minimal x11 dependencies
  apt: name={{item}} update_cache=yes cache_valid_time=3600
  with_items:
  - mesa-utils
  - x11-utils
  - pulseaudio-utils
  - libasound2
  - libdbus-glib-1-2
  - libgtk2.0-0
  - libcanberra-gtk-module

- name: install x11 devtools
  apt: name={{item}} update_cache=yes cache_valid_time=3600
  with_items:
  - meld
  - gitg
  - tortoisehg

- name: install x11 utils
  apt: name={{item}} update_cache=yes cache_valid_time=3600
  with_items:
  - xsel
  - xpra
